### ISSUE TITLE
3 G's are no longer needed in outdoor gastronomy (at least in some parts of Germany)

### ISSUE THREAD

**Issue by MaxKannNichtCoden** [railslove/recover-backlog#163] opened 2021-06-07 10:54 UTC

**Comment by MaxKannNichtCoden** [comment] 2021-06-07 10:55
We have received feedback from some users that this function is no longer needed on terraces and in beer gardens.
Guests sometimes refuse to check in then

**Comment by salimhb** [comment] 2021-06-10 13:51
duplicate of #161

**Closed as completed** 2021-06-10 13:51 UTC
